name: ReportsSystem
version: '${project.version}'
main: me.gpmcplugins.reportssystem.reportssystem.ReportsSystem
api-version: 1.18
authors: [ Pythontest, Idont, Ssz256 ]
description: Provides easy report system


commands:
  report-info:
    description: Pokazuje ważną informację o pluginie
    usage: /report-info
    permission: reportsystem.help
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
    aliases: [ r-info, ri]
  report:
    description: Reportuje użytkownika wskazanego w komendzie.
    usage: /report User <nick>
    permission:  reportsystem.report
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
    aliases:
      - r
  report-continue:
    description: report continue.
    usage: to jest komenda dla gui nie powinienes jej wpisywac w chat
    permission: reportsystem.report
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
  report-list:
    description: Pokazuje listę twoich zgłoszeń
    usage: /report-list <wszystkie|otwarte|zamknięte> <strona>
    permission: reportsystem.report
    permission-message:  Nev nie lubi naszych pluginów i to zablokował.
    aliases: [r-list, r-l, rl]
  report-review:
    description: Pozwala przeglądać reporty
    usage: /report-review
    permission: reportsystem.reportreview
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
    aliases: [r-review, rr]
  report-view-death-inventory:
    description: Pozwala zobaczyć swoje inventory po śmierci
    usage: /report-view-death-inventory
    permission: reportsystem.report
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
    aliases: [ r-view-death-inventory, r-death-inventory, rdi]
  report-help:
    description: Wyświetla pomoc
    usage: /report-help
    permission: reportsystem.help
    permission-message: Nev nie lubi naszych pluginów i to zablokował
    aliases: [ r-help, rh]
  report-update:
    description: Aktualizuje plugin
    usage: /update
    permission: reportsystem.update
    permission-message: Nie powinienes korzystac z tej komendy
    aliases: [ ReportsSystem-update, rsupdate, rsu]
permissions:
  reportsystem.report:
    default: true
    description: Daje użytkownikowi dostęp do /report
  reportsystem.reportreview:
    default: op
    description: Daje użytkownikowi dostęp do /report-review
  reportsystem.help:
    default: true
    description: Daje dostęp do /report-help
  reportsystem.notification:
    default: op
    description: Wysyła powiadomienia o nowych reportach
  reportsystem.update:
    default: op
    description: Dodaje dostęp do komendy /update