name: ReportsSystem
version: '${project.version}'
main: me.gpmcplugins.reportssystem.reportssystem.ReportsSystem
api-version: 1.18
authors: [ Pythontest, Idont ]
description: Provides easy report system
