name: ReportsSystem
version: '${project.version}'
main: me.gpmcplugins.reportssystem.reportssystem.ReportsSystem
api-version: 1.18
authors: [ Pythontest, Idont, Ssz256 ]
description: Provides easy report system


commands:
  report:
    description: Reportuje użytkownika wskazanego w komendzie.
    usage: /report
    permission:  reportsystem.report
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
  reportcontinue:
    description: report continue.
    usage: /reportcontinue
    permission: reportsystem.report
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
  report-review:
    description: Pozwala przeglądać reporty
    usage: /report-review
    permission: reportsystem.reportreview
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
  help:
    description: Wyświetla pomoc
    usage: /help
    permission: reportsystem.help
    permission-message: Nev nie lubi naszych pluginów i to zablokował
permissions:
  reportsystem.report:
    default: true
    description: Daje użytkownikowi dostęp do /report
  reportsystem.reportreview:
    default: op
    description: Daje użytkownikowi dostęp do /report-review