name: ReportsSystem
version: '${project.version}'
main: me.gpmcplugins.reportssystem.reportssystem.ReportsSystem
api-version: 1.18
authors: [ Pythontest, Idont ]
description: Provides easy report system


commands:
  report:
    description: Reportuje użytkownika wskazanego w komendzie.
    usage: /report
    permission:  reportsystem.report
permissions:
  reportsystem.report:
    default: true
    description: Daje użytkownikowi dostęp do /report