name: ReportsSystem
version: '${project.version}'
main: me.gpmcplugins.reportssystem.reportssystem.ReportsSystem
api-version: 1.18
authors: [ Pythontest, Idont, Ssz256 ]
description: Provides easy report system


commands:
  report-info:
    description: Pokazuje ważną informację o pluginie
    usage: /report-info
    permission: reportsystem.help
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
  report:
    description: Reportuje użytkownika wskazanego w komendzie.
    usage: /report User <nick>
    permission:  reportsystem.report
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
  report-continue:
    description: report continue.
    usage: to jest komenda dla gui nie powinienes jej wpisywac w chat
    permission: reportsystem.report
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
  report-review:
    description: Pozwala przeglądać reporty
    usage: /report-review
    permission: reportsystem.reportreview
    permission-message: Nev nie lubi naszych pluginów i to zablokował.
  viewDeathInventory:
    description: Pozwala zobaczyć swoje inventory po śmierci
    usage: /report-view-death-inventory
    permission: reportsystem.report
  report-help:
    description: Wyświetla pomoc
    usage: /report-help
    permission: reportsystem.help
    permission-message: Nev nie lubi naszych pluginów i to zablokował
permissions:
  reportsystem.report:
    default: true
    description: Daje użytkownikowi dostęp do /report
  reportsystem.reportreview:
    default: op
    description: Daje użytkownikowi dostęp do /report-review
  reportsystem.help:
    default: true
    description: Daje dostęp do /report-help
  reportsystem.notification:
    default: op
    description: Wysyła powiadomienia o nowych reportach